"""
Attendees router.

POST /attendees/register           — customer registers for an event
GET  /attendees/my                 — customer's own registrations (with event details)
GET  /attendees/{id}/status        — lightweight status poll (customer or admin)
GET  /attendees/{id}/badge         — serve badge PDF from R2 (only when checked_in)
"""

import asyncio
import logging
from typing import List

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import RedirectResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models import Attendee, Event
from app.schemas import (
    AttendeeRegisterRequest,
    AttendeeOut,
    AttendeeWithEventOut,
    AttendeeStatusOut,
)
from app.auth.utils import get_current_user
from app.services.qr import generate_qr
from app.services.email import send_confirmation_email

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/attendees", tags=["attendees"])


@router.post("/register", response_model=AttendeeOut, status_code=status.HTTP_201_CREATED)
async def register_for_event(
    body: AttendeeRegisterRequest,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """Register the authenticated customer for an event."""
    # Verify event exists and is published
    event = (
        await db.execute(select(Event).where(Event.id == body.event_id))
    ).scalar_one_or_none()
    if not event:
        raise HTTPException(status_code=404, detail="Event not found.")
    if not event.is_published:
        raise HTTPException(status_code=400, detail="Event is not open for registration.")

    # Prevent duplicate registration
    existing = (
        await db.execute(
            select(Attendee).where(
                Attendee.user_id == current_user["sub"],
                Attendee.event_id == body.event_id,
            )
        )
    ).scalar_one_or_none()
    if existing:
        raise HTTPException(
            status_code=409,
            detail="You are already registered for this event.",
        )

    # Create attendee record (qr_code_id generated by model default)
    attendee = Attendee(
        user_id=current_user["sub"],
        event_id=body.event_id,
        name=body.name,
        profession=body.profession,
    )
    db.add(attendee)
    await db.commit()
    await db.refresh(attendee)

    # Generate QR code PNG (synchronous — fast, <100ms)
    try:
        generate_qr(attendee.qr_code_id)
    except Exception as exc:
        logger.error("QR generation failed for attendee %s: %s", attendee.id, exc)

    # Send confirmation email — fire-and-forget in thread executor, never blocks registration
    loop = asyncio.get_event_loop()
    loop.run_in_executor(
        None,
        lambda: _send_email_safe(
            to=current_user["email"],
            name=attendee.name,
            event=event,
        ),
    )

    return attendee


def _send_email_safe(to: str, name: str, event: Event) -> None:
    """Thin wrapper so email errors never propagate to the caller."""
    try:
        send_confirmation_email(
            to=to,
            name=name,
            event_title=event.title,
            event_date=event.date,
            event_location=event.location or "",
            qr_url="",  # customer views QR on their dashboard
        )
    except Exception as exc:
        logger.error("Email send error: %s", exc)


@router.get("/my", response_model=List[AttendeeWithEventOut])
async def my_registrations(
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """Return all registrations for the currently authenticated user, with event details."""
    from sqlalchemy.orm import selectinload
    result = await db.execute(
        select(Attendee)
        .options(selectinload(Attendee.event))
        .where(Attendee.user_id == current_user["sub"])
        .order_by(Attendee.created_at.desc())
    )
    return result.scalars().all()


@router.get("/{attendee_id}/status", response_model=AttendeeStatusOut)
async def get_attendee_status(
    attendee_id: str,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """
    Lightweight status poll — used by both admin scan page and customer dashboard.
    Customers can only poll their own records; admins can poll any.
    """
    attendee = (
        await db.execute(select(Attendee).where(Attendee.id == attendee_id))
    ).scalar_one_or_none()
    if not attendee:
        raise HTTPException(status_code=404, detail="Attendee not found.")

    # Customers may only see their own records
    if current_user["role"] == "customer" and attendee.user_id != current_user["sub"]:
        raise HTTPException(status_code=403, detail="Access denied.")

    return attendee


@router.delete("/{attendee_id}", status_code=status.HTTP_204_NO_CONTENT)
async def unregister(
    attendee_id: str,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """
    Customer cancels their registration. Only allowed while status is 'registered'.
    Blocked if status is 'pending' (badge generating) or 'checked_in'.
    """
    attendee = (
        await db.execute(select(Attendee).where(Attendee.id == attendee_id))
    ).scalar_one_or_none()
    if not attendee:
        raise HTTPException(status_code=404, detail="Registration not found.")

    # Customers can only unregister their own records
    if current_user["role"] == "customer" and attendee.user_id != current_user["sub"]:
        raise HTTPException(status_code=403, detail="Access denied.")

    if attendee.status in ("pending", "checked_in"):
        raise HTTPException(
            status_code=409,
            detail="You cannot unregister after check-in has started.",
        )

    await db.delete(attendee)
    await db.commit()


@router.get("/{attendee_id}/badge")
async def download_badge(
    attendee_id: str,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    """
    Serve the badge PDF by redirecting to its stored R2 URL.

    The PDF is generated exactly once at check-in time and stored permanently
    in Cloudflare R2. This endpoint simply reads badge_pdf_url from the
    attendee record and issues a 302 redirect — no PDF generation happens here.

    Returns 404 if the attendee is not yet checked in or the badge URL is missing.
    """
    attendee = (
        await db.execute(select(Attendee).where(Attendee.id == attendee_id))
    ).scalar_one_or_none()

    if not attendee:
        raise HTTPException(status_code=404, detail="Attendee not found.")

    if current_user["role"] == "customer" and attendee.user_id != current_user["sub"]:
        raise HTTPException(status_code=403, detail="Access denied.")

    if attendee.status != "checked_in" or not attendee.badge_pdf_url:
        raise HTTPException(
            status_code=404,
            detail="Badge not ready yet. Check in first.",
        )

    logger.info("Badge redirect for attendee=%s → %s", attendee_id, attendee.badge_pdf_url)
    return RedirectResponse(url=attendee.badge_pdf_url, status_code=302)
